name: Generate Alcuin Calendar

on:
  schedule:
    - cron: "0 5 * * *"   # Tous les jours à 5h UTC (7h heure française)
  workflow_dispatch:       # Permet aussi de lancer à la main depuis GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 ics

      - name: Run script
        env:
          ALCUIN_USERNAME: ${{ secrets.ALCUIN_USERNAME }}
          ALCUIN_PASSWORD: ${{ secrets.ALCUIN_PASSWORD }}
        run: agenda alcuin purpan.py

      - name: Upload ICS to GitHub Pages
        run: |
          mkdir -p public
          mv alcuin_planning.ics public/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
